feat: use strongly typed `kommunikationsrichtungen` instead of stringly typed `kommunikation_von` in AHB views (#203)
* feat: use strongly typed `kommunikationsrichtungen` instead of stringly typed `kommunikation_von` in AHB views

The field was introduced in #181 (v0.24) and contains the same information as `kommunikation_von` but in a way that can be processed without manually splitting commas and slashes and newlines and ...

This change is "a little bit breaking" for all those who rely on `ahb_hierarchy_materialized` directly and those who consume `v_ahbtabellen` direction column.
The column is no longer explicitly indexed by SQLmodel because: "RuntimeError: Passing index is not supported when also passing a sa_column"

see https://github.com/Hochfrequenz/ahb-tabellen/issues/704#issuecomment-3521368623

* fix outdated test

 unittests/test_sqlmodels_anwendungshandbuch.py:210: error: "AhbHierarchyMaterialized" has no attribute "kommunikation_von"  [attr-defined]

---------

Co-authored-by: Konstantin <konstantin.klein+github@hochfrequenz.de>